name: .NET Core

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install dependencies
      run: dotnet restore Source/GravityHelper.csproj
    - name: Build
      run: dotnet build Source/GravityHelper.csproj --configuration Release --no-restore
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GravityHelper
        path: |
          everest.yaml
          bin/GravityHelper.dll
          bin/GravityHelper.pdb
          Ahorn/**/*
          Audio/**/*
          Dialog/**/*
          Graphics/**/*
          Loenn/**/*