name: Tagged Release
on:
  workflow_dispatch:
  push:
    tags: ['*']

jobs:
  build:
    name: Build and Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Fetch all tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
    - name: Get current tag
      run: echo "CURRENT_TAG=$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV
    - name: Install dependencies
      run: dotnet restore Source/GravityHelper.csproj
    - name: Build
      run: dotnet build Source/GravityHelper.csproj --configuration Release -p:version=${{env.CURRENT_TAG}} --no-restore
    - name: Package
      run: zip -q -r GravityHelper.zip everest.yaml bin/GravityHelper.dll bin/GravityHelper.pdb Ahorn Audio Dialog Effects Graphics Loenn
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          Tagged release ${{ github.ref_name }}
        draft: true
        prerelease: true
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./GravityHelper.zip
        asset_name: GravityHelper.zip
        asset_content_type: application/zip
